config/routes.rb
Rails.application.routes.draw do
  namespace :olympics do
    resources :teams
    resources :matches, only: [:index, :update]

    get "/scoreboard", to: "scoreboard#scoreboard"
    get "/generate_brackets", to: "scoreboard#generate_form"
    post "/generate_brackets", to: "scoreboard#generate_brackets"
    get "/fetch_now_playing" => 'scoreboard#fetch_now_playing', as: 'fetch_now_playing'
    get "/fetch_on_deck" => 'scoreboard#fetch_on_deck'
    get "/fetch_rankings" => 'scoreboard#fetch_rankings'
    get "/fetch_tiebreaker" => 'scoreboard#fetch_tiebreaker'
    get "/fetch_latest_updated_at" => 'scoreboard#fetch_latest_updated_at'
  end

  namespace :advocate do
    get "/schedule", to: "schedule#show"
    get "/aggregate_report", to: "schedule#aggregate_report"
    get "/monthly_report", to: "schedule#monthly_report"
  end

  namespace :etoh do
    get "/drinks", to: "drinks#index"
    post "/drinks", to: "drinks#create"
    get "/delete_drink", to: "drinks#destroy"
  end

  namespace :wrestle_bet do
    resources :prop_bets
    resources :spread_bets
    resources :matches
    resources :wrestlers
    resources :tournaments, only: [:update, :show]
    get "/tournaments", to: "tournaments#index"
    get "/tournaments/:id/betslip", to: "tournaments#betslip", as: :betslip
    get "/tournaments/:id/display", to: "tournaments#display", as: :display
    get "/tournaments/:id/user_links", to: "tournaments#user_links", as: :user_links
    get "/tournaments/:id/scorecard", to: "tournaments#scorecard", as: :scorecard
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  get "/access_denied", to: "application#access_denied"

  #### <Wrestling>
  root "matches#index"

  get "/individual_rankings/:weight", to: "wrestlers#individual_rankings", as: "individual_rankings"

  get "/matches/preview", to: "matches#preview", as: "preview"
  get "/matches/:id", to: "matches#edit", as: "match"
  patch "/matches/:id", to: "matches#update", as: "update_match"

  get "/colleges", to: "colleges#index", as: "colleges"
  get "/colleges/:id", to: "colleges#show", as: "college"
  #### </Wrestling>
end

app/models/etoh.rb
module Etoh
  def self.table_name_prefix
    "etoh_"
  end
end

app/models/etoh/drink.rb
class Etoh::Drink < ApplicationRecord
  def self.metabolize!
    return unless can_metabolize?

    eligible = Etoh::Drink
      .where(metabolized_at: nil)
      .where("consumed_at < ?", Time.now.advance(minutes: -60))
      .order("consumed_at ASC")
      .first

    return unless eligible.present?

    metabolized_time = if last_metabolized_at == 0
      eligible.consumed_at + 60.minutes
    else
      [
        last_metabolized_at + 60.minutes,
        eligible.consumed_at + 60.minutes
      ].max
    end
    eligible.update_attribute(:metabolized_at, metabolized_time)

    Rails.logger.info "[METABOLIZE] metabolized #{eligible}"

    metabolize! if can_metabolize?
  end

  def self.last_metabolized_at
    Etoh::Drink.maximum(:metabolized_at) || 0
  end

  def self.can_metabolize?
    (Time.now - last_metabolized_at) > 60.minutes
  end

  def metabolized?
    metabolized_at.present?
  end
end

app/models/etoh/drinks_presenter.rb
class Etoh::DrinksPresenter
  LIMIT = 5
  attr_reader :drinks

  def initialize
    @drinks = Etoh::Drink
      .where("consumed_at > ?", Time.now.advance(hours: -12))
      .order("consumed_at DESC")
  end

  def current_drinks
    @drinks.count
  end

  def session_start
    @drinks.map(&:consumed_at).min
  end

  def session_last_metabolized_at
    @drinks.map(&:metabolized_at).compact.min || 0
  end

  def session_length
    if session_start.present?
      ((Time.now - session_start) /  1.hour)
    else
      0
    end
  end

  def session_hours
    session_length.floor
  end

  def recharge_in
    return 0 if @drinks.length == 0

    if session_last_metabolized_at == 0
      60 - ((Time.now - session_start) /  1.minute).round
    else
      60 - ((Time.now - session_last_metabolized_at) / 1.minutes).round
    end
  end

  def non_metabolized_drinks
    @drinks.reject { |drink| drink.metabolized? }
  end

  def drinks_remaining
    LIMIT - non_metabolized_drinks.length
  end
end

app/controllers/etoh/application_controller.rb
class Etoh::ApplicationController < ApplicationController
  layout "etoh/application"
end

app/controllers/etoh/drinks_controller.rb
class Etoh::DrinksController < Etoh::ApplicationController
  def index
    Etoh::Drink.metabolize!
    @drink = Etoh::Drink.new
    @presenter = Etoh::DrinksPresenter.new
  end

  def create
    Etoh::Drink.create!(drink_params)
    redirect_to etoh_drinks_path
  end

  def destroy
    Etoh::Drink.find(params[:id]).destroy
    redirect_to etoh_drinks_path
  end

  def drink_params
    raw_consumed_at = params[:etoh_drink][:consumed_at]
    if raw_consumed_at.present?
      params[:etoh_drink][:consumed_at] = Time.now.advance(minutes: raw_consumed_at.to_i)
    end

    params.require(:etoh_drink).permit(:consumed_at)
  end
end

app/views/etoh/drinks/index.html.erb
<h1 id="clock"></h1>

<%= @presenter.current_drinks %> drinks in 
<%= pluralize(@presenter.session_length.round(1), "hour") %>
<br/>
<%= pluralize(@presenter.drinks_remaining, "drinks") %> remaining

<div id="fuel_bar">
  <% (1..Etoh::DrinksPresenter::LIMIT).to_a.each do |i| %>
    <% if i <= @presenter.drinks_remaining %>
      <div class="cell full"></div>
    <% else %>
      <div class="cell"></div>
    <% end %>
  <% end %>
</div>

<div class="clear"></div>
Recharge in <%= @presenter.recharge_in %>m

<% [0, -15, -30, -45, -60].each do |minutes| %>
  <%= form_with(url: etoh_drinks_path, model: @drink) do |form| %>
    <%= form.hidden_field :consumed_at, value: minutes %>
    <% if minutes == 0 %>
      <%= form.submit "Drank drink" %>
    <% else %>
      <%= form.submit "Drank drink (#{minutes}m)" %>
    <% end %>
  <% end %>
<% end %>

<% @presenter.drinks.each do |drink| %>
  <div>
    <span class="<%= drink.metabolized? ? "metabolized" : "" %>">
      Drink logged <%= drink.consumed_at.in_time_zone('US/Central').strftime("%H:%M") %>
    </span>
    <%= link_to("[ X ]", etoh_delete_drink_path(id: drink.id), class: "delete_drink") %>

    <% if drink.metabolized? %>
      <%= drink.metabolized_at.in_time_zone('US/Central').strftime("%H:%M") %>
    <% end %>
  </div>
<br/>
<% end %>