config/routes.rb
Rails.application.routes.draw do
  namespace :olympics do
    resources :teams
    resources :matches, only: [:index, :update]

    get "/scoreboard", to: "scoreboard#scoreboard"
    get "/generate_brackets", to: "scoreboard#generate_form"
    post "/generate_brackets", to: "scoreboard#generate_brackets"
    get "/fetch_now_playing" => 'scoreboard#fetch_now_playing', as: 'fetch_now_playing'
    get "/fetch_on_deck" => 'scoreboard#fetch_on_deck'
    get "/fetch_rankings" => 'scoreboard#fetch_rankings'
    get "/fetch_tiebreaker" => 'scoreboard#fetch_tiebreaker'
    get "/fetch_latest_updated_at" => 'scoreboard#fetch_latest_updated_at'
  end

  namespace :advocate do
    get "/schedule", to: "schedule#show"
    get "/aggregate_report", to: "schedule#aggregate_report"
    get "/monthly_report", to: "schedule#monthly_report"
  end

  namespace :etoh do
    get "/drinks", to: "drinks#index"
    post "/drinks", to: "drinks#create"
    get "/delete_drink", to: "drinks#destroy"
  end

  namespace :wrestle_bet do
    resources :prop_bets
    resources :spread_bets
    resources :matches
    resources :wrestlers
    resources :tournaments, only: [:update, :show]
    get "/tournaments", to: "tournaments#index"
    get "/tournaments/:id/betslip", to: "tournaments#betslip", as: :betslip
    get "/tournaments/:id/display", to: "tournaments#display", as: :display
    get "/tournaments/:id/user_links", to: "tournaments#user_links", as: :user_links
    get "/tournaments/:id/scorecard", to: "tournaments#scorecard", as: :scorecard
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  get "/access_denied", to: "application#access_denied"

  #### <Wrestling>
  root "matches#index"

  get "/individual_rankings/:weight", to: "wrestlers#individual_rankings", as: "individual_rankings"

  get "/matches/preview", to: "matches#preview", as: "preview"
  get "/matches/:id", to: "matches#edit", as: "match"
  patch "/matches/:id", to: "matches#update", as: "update_match"

  get "/colleges", to: "colleges#index", as: "colleges"
  get "/colleges/:id", to: "colleges#show", as: "college"
  #### </Wrestling>
end

app/models/wrestle_bet.rb
module WrestleBet
  def self.table_name_prefix
    "wrestle_bet_"
  end
end

app/controllers/wrestle_bet/application_controller.rb
class WrestleBet::ApplicationController < ApplicationController
  layout "wrestle_bet/application"
  before_action :set_tournament

  def set_tournament
    @tournament = WrestleBet::Tournament.first
  end
end

app/controllers/wrestle_bet/matches_controller.rb
class WrestleBet::MatchesController < WrestleBet::ApplicationController
  before_action :set_wrestle_bet_match, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_admin!, only: [:show]

  # GET /wrestle_bet/matches or /wrestle_bet/matches.json
  def index
    @wrestle_bet_matches = WrestleBet::Match.order("weight ASC")
      .all
      .sort_by { |m| m.completed? ? 1 : 0 }

    @tournament = WrestleBet::Tournament.first!
  end

  # GET /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def show
    respond_to do |format|
      format.html { render  }
      format.json do
        render json: @wrestle_bet_match.as_json(
          only: [:id, :home_score, :away_score]
        )
      end
    end
  end

  # GET /wrestle_bet/matches/new
  def new
    @wrestle_bet_match = WrestleBet::Match.new
  end

  # GET /wrestle_bet/matches/1/edit
  def edit
  end

  # POST /wrestle_bet/matches or /wrestle_bet/matches.json
  def create
    @wrestle_bet_match = WrestleBet::Match.new(wrestle_bet_match_params)

    respond_to do |format|
      if @wrestle_bet_match.save
        format.html { redirect_to wrestle_bet_match_url(@wrestle_bet_match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @wrestle_bet_match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_match.update(wrestle_bet_match_params)
        format.html { redirect_to wrestle_bet_matches_url, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @wrestle_bet_match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def destroy
    @wrestle_bet_match.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_match
      @wrestle_bet_match = WrestleBet::Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_match_params
      params.require(:wrestle_bet_match).permit(:weight, :started, :home_wrestler_id, :away_wrestler_id, :home_score, :away_score, :tournament_id, :spread)
    end
end

app/controllers/wrestle_bet/prop_bets_controller.rb
class WrestleBet::PropBetsController < WrestleBet::ApplicationController
  skip_before_action :authenticate_admin!, only: [:create, :update]
  before_action :authenticate_user!, only: [:create, :update]
  before_action :set_wrestle_bet_prop_bet, only: %i[ show edit update destroy ]
  before_action :verify_tournament_has_not_started, only: %i[ create update ]

  # GET /wrestle_bet/prop_bets or /wrestle_bet/prop_bets.json
  def index
    @wrestle_bet_prop_bets = WrestleBet::PropBet.all
  end

  # GET /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def show
  end

  # POST /wrestle_bet/prop_bets or /wrestle_bet/prop_bets.json
  def create
    @bet = WrestleBet::PropBet.new(wrestle_bet_prop_bet_params)
    @bet.user_id = current_user.id
    WrestleBet::PropBet.where(
      user_id: current_user.id,
      tournament_id: @bet.tournament_id,
    ).destroy_all

    respond_to do |format|
      if @bet.save
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.tournament_id),
          notice: "Prop bets updated"
        }
        format.json { render :show, status: :created, location: @bet }
      else
        @bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.tournament_id),
          alert: "failed to place bet"
        }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_prop_bet.update(wrestle_bet_prop_bet_params)
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @wrestle_bet_prop_bet.tournament_id),
          notice: "Prop bets updated"
        }
        format.json { render :show, status: :ok, location: @wrestle_bet_prop_bet }
      else
        @wrestle_bet_prop_bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @wrestle_bet_prop_bet.tournament_id),
          alert: "failed to update prop bets"
        }
        format.json { render json: @wrestle_bet_prop_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def destroy
    @wrestle_bet_prop_bet.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_prop_bets_url, notice: "Prop bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_prop_bet
      @wrestle_bet_prop_bet = WrestleBet::PropBet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_prop_bet_params
      params.require(:wrestle_bet_prop_bet).permit(:tournament_id, :jesus, :exposure, :challenges)
    end

    def verify_tournament_has_not_started
      @tournament = WrestleBet::Tournament.find(wrestle_bet_prop_bet_params[:tournament_id])
      if @tournament.started?
          redirect_to wrestle_bet_betslip_url(id: @tournament.id),
            alert: "Tournament has already started"
      end
    end
end

app/controllers/wrestle_bet/spread_bets_controller.rb
class WrestleBet::SpreadBetsController < WrestleBet::ApplicationController
  skip_before_action :authenticate_admin!, only: [:create]
  before_action :authenticate_user!, only: [:create]

  before_action :set_wrestle_bet_spread_bet, only: %i[ show edit update destroy ]

  before_action :verify_match_has_not_started, only: %i[ create ]

  # GET /wrestle_bet/spread_bets or /wrestle_bet/spread_bets.json
  def index
    @wrestle_bet_spread_bets = WrestleBet::SpreadBet.all
  end

  # GET /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def show
  end

  # GET /wrestle_bet/spread_bets/new
  def new
    @wrestle_bet_spread_bet = WrestleBet::SpreadBet.new
  end

  # GET /wrestle_bet/spread_bets/1/edit
  def edit
  end

  # POST /wrestle_bet/spread_bets or /wrestle_bet/spread_bets.json
  def create
    @bet = WrestleBet::SpreadBet.new(wrestle_bet_spread_bet_params)
    @bet.user_id = current_user.id
    WrestleBet::SpreadBet.where(
      user_id: current_user.id,
      match_id: @bet.match_id,
    ).destroy_all

    respond_to do |format|
      if @bet.save
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.match.tournament_id),
          notice: "#{@bet.label} placed"
        }
        format.json { render json: {status: :created}, status: :created }
      else
        @bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.match.tournament_id),
          alert: "failed to place bet"
        }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_spread_bet.update(wrestle_bet_spread_bet_params)
        format.html { redirect_to wrestle_bet_spread_bet_url(@wrestle_bet_spread_bet), notice: "Spread bet was successfully updated." }
        format.json { render :show, status: :ok, location: @wrestle_bet_spread_bet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_spread_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def destroy
    @wrestle_bet_spread_bet.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_spread_bets_url, notice: "Spread bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_spread_bet
      @wrestle_bet_spread_bet = WrestleBet::SpreadBet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_spread_bet_params
      params.require(:wrestle_bet_spread_bet).permit(:match_id, :wager)
    end

    def verify_match_has_not_started
      @match = WrestleBet::Match.find(wrestle_bet_spread_bet_params[:match_id])
      if @match.started?
        respond_to do |format|
          format.html {
            redirect_to wrestle_bet_betslip_url(id: @match.tournament_id),
              alert: "Match has already started"
          }
          format.json {
            render json: {error: "Match has already started"}, status: 422
          }
        end
      end
    end
end

app/controllers/wrestle_bet/tournaments_controller.rb
class WrestleBet::TournamentsController < WrestleBet::ApplicationController
  skip_before_action :authenticate_admin!, only: [:betslip, :show, :scorecard]
  before_action :_authenticate_user_from_link, only: [:betslip]
  before_action :authenticate_user!, only: [:betslip, :scorecard]

  def index
  end

  def betslip
    @tournament = WrestleBet::Tournament.find(params[:id])
    @matches = @tournament.matches.order("weight ASC")
      .all
      .sort_by { |m| m.completed? ? 1 : 0 }

    @prop_bet = WrestleBet::PropBet.where(
      user_id: current_user.id,
      tournament_id: @tournament.id
    ).first

    unless @prop_bet.present?
      @prop_bet = WrestleBet::PropBet.new(tournament_id: @tournament.id)
    end
  end

  def user_links
    @tournament = WrestleBet::Tournament.find(params[:id])
  end

  def display
    @tournament = WrestleBet::Tournament.find(params[:id])
    @match = @tournament.current_match

    if @match.present?
      render
    else
      @tournament = WrestleBet::Tournament.find(params[:id])
      @leaderboard = WrestleBet::Leaderboard.new(@tournament)
      render "scorecard"
    end
  end

  def show
    @tournament = WrestleBet::Tournament.find(params[:id])
    render json: @tournament.as_json(
      only: [:id, :jesus, :exposure, :challenges],
    ).merge(match_in_progress: @tournament.current_match.present?)
  end

  def update
    @tournament = WrestleBet::Tournament.find(params[:id])
    @tournament.jesus = params[:wrestle_bet_tournament][:jesus]
    @tournament.exposure = params[:wrestle_bet_tournament][:exposure]
    @tournament.challenges = params[:wrestle_bet_tournament][:challenges]
    @tournament.save!

    redirect_to wrestle_bet_matches_url, notice: "Updated"
  end

  def scorecard
    @tournament = WrestleBet::Tournament.find(params[:id])
    @leaderboard = WrestleBet::Leaderboard.new(@tournament)
  end

  def _authenticate_user_from_link
    return if current_user.present?
    return unless params[:c].present?

    email = Base64.decode64(params[:c])
    user = User.where(email: email).first!
    sign_in(user)
  end
end

app/controllers/wrestle_bet/wrestlers_controller.rb
class WrestleBet::WrestlersController < WrestleBet::ApplicationController
  before_action :set_wrestle_bet_wrestler, only: %i[ show edit update destroy ]

  # GET /wrestle_bet/wrestlers or /wrestle_bet/wrestlers.json
  def index
    @wrestle_bet_wrestlers = WrestleBet::Wrestler.all
  end

  # GET /wrestle_bet/wrestlers/1 or /wrestle_bet/wrestlers/1.json
  def show
  end

  # GET /wrestle_bet/wrestlers/new
  def new
    @wrestle_bet_wrestler = WrestleBet::Wrestler.new
    @colleges = College.pluck(:name, :id)
  end

  # GET /wrestle_bet/wrestlers/1/edit
  def edit
    @colleges = College.pluck(:name, :id)
  end

  # POST /wrestle_bet/wrestlers or /wrestle_bet/wrestlers.json
  def create
    @wrestle_bet_wrestler = WrestleBet::Wrestler.new(wrestle_bet_wrestler_params)

    respond_to do |format|
      if @wrestle_bet_wrestler.save
        format.html { redirect_to wrestle_bet_wrestler_url(@wrestle_bet_wrestler), notice: "Wrestler was successfully created." }
        format.json { render :show, status: :created, location: @wrestle_bet_wrestler }
      else
        @colleges = College.pluck(:name, :id)
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_wrestler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/wrestlers/1 or /wrestle_bet/wrestlers/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_wrestler.update(wrestle_bet_wrestler_params)
        format.html { redirect_to wrestle_bet_wrestler_url(@wrestle_bet_wrestler), notice: "Wrestler was successfully updated." }
        format.json { render :show, status: :ok, location: @wrestle_bet_wrestler }
      else
        @colleges = College.pluck(:name, :id)
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_wrestler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/wrestlers/1 or /wrestle_bet/wrestlers/1.json
  def destroy
    @wrestle_bet_wrestler.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_wrestlers_url, notice: "Wrestler was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_wrestler
      @wrestle_bet_wrestler = WrestleBet::Wrestler.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_wrestler_params
      params.require(:wrestle_bet_wrestler).permit(:name, :college_id, :avatar)
    end
end

app/helpers/wrestle_bet/matches_helper.rb
module WrestleBet::MatchesHelper
end

app/helpers/wrestle_bet/prop_bets_helper.rb
module WrestleBet::PropBetsHelper
end

app/helpers/wrestle_bet/spread_bets_helper.rb
module WrestleBet::SpreadBetsHelper
  def user_betslip_link(user, tournament)
    link_to(
      user.email,
      wrestle_bet_betslip_url(id: tournament.id, c: user.encoded_email)
    )
  end
end

app/helpers/wrestle_bet/wrestlers_helper.rb
module WrestleBet::WrestlersHelper
end

app/views/wrestle_bet/tournaments/_prop_bet_animations.html.erb
<div class="wrestle_bet_prop_bet_animation" id="wrestle_bet_jesus">
  <%= image_tag "wrestle_bet/jesus_2.png" %> 
</div>

<div class="wrestle_bet_prop_bet_animation" id="wrestle_bet_exposure">
  <%= image_tag "wrestle_bet/exposure.png" %> 
</div>

<div class="wrestle_bet_prop_bet_animation" id="wrestle_bet_challenge">
  <%= image_tag "wrestle_bet/challenge.png" %> 
</div>

app/views/wrestle_bet/tournaments/betslip.html.erb
<div id="wrestle_bet_betslip">

<h1><%= current_user.handle %> Betslip</h1>

<%= image_tag current_user.avatar.variant(:thumb) %>

<div id="wrestle_bet_prop_bets">
  <h2>Prop Bets</h2>
  <div id="prop_bet_toggle">
    <% if @tournament.started? %>
      <div class="prop_bets_hide_show <%= @tournament.started? ? "" : "hidden" %>">
        Show bets
      </div>
      <div class="prop_bets_hide_show <%= @tournament.started? ? "hidden" : "" %>">
        Hide bets
      </div>
    <% end %>
  </div>
  <div id="prop_bet_content" class="<%= @tournament.started? ? "hidden" : "" %>">
    <p>
      These must be entered before the first match starts
    </p>
    <%= render partial: "wrestle_bet/prop_bets/form", locals: {prop_bet: @prop_bet} %>
  </div>
</div>

<div id="wrestle_bet_spread_bets">
<h2>Match Bets</h2>
<p>
  These can be entered or altered up until each match begins
</p>

<table>

  <% @matches.each do |match| %>

  <% current_bet = match.current_bet_for_user(current_user) %>

  <tr>
    <th colspan='2'>
      <%= match.weight %> lbs <br/>
      <%= match.home_wrestler.name %> 
      (<%= match.home_wrestler.college.name %>) 

      <br/>

      <%= match.away_wrestler.name %> 
      (<%= match.away_wrestler.college.name %>)

      <% if match.completed? %>
        <br/>Final score: <%= match.home_score %> to <%= match.away_score %>
      <% end %>
    </th>
  </tr>

  <tr>
    <td colspan='2'>
      <% if match.completed? && current_bet.present? %>

        <% if current_bet.won? %>
          <div class="wrestle_bet_bet_outcome wrestle_bet_bet_won">
            Bet Won
          </div>
        <% else %>
          <div class="wrestle_bet_bet_outcome wrestle_bet_bet_lost">
            Bet Lost
          </div>
        <% end %>
      <% elsif match.completed? %>
        match concluded
      <% elsif match.started? %>
        betting closed, match is in progress
      <% else %>
        betting open
      <% end %>
    </td>
  </tr>

  <tr>
    <td class="wrestle_bet_wrestler <%= current_bet.present? && current_bet.wager == "home" ? "current_bet" : "" %>">
      <%= image_tag match.home_wrestler.avatar.variant(:thumb) %><br/>
      <%= match.home_wrestler.name %> <br/>
      <%= match.spread < 0 ? match.spread : "+#{match.spread}" %> <br/>

      <% if match.open_for_betting? %>
        <%= form_with(model: WrestleBet::SpreadBet.new(match: match, wager: "home")) do |form| %>
          <%= form.hidden_field :match_id %>
          <%= form.hidden_field :wager %>

          <div>
            <%= form.submit "Bet on #{match.home_wrestler.name}" %>
          </div>
        <% end %>
      <% end %>
    </td>

    <td class="wrestle_bet_wrestler <%= current_bet.present? && current_bet.wager == "away" ? "current_bet" : "" %>">
      <%= image_tag match.away_wrestler.avatar.variant(:thumb) %><br/>
      <%= match.away_wrestler.name %> <br/>
      <%= match.spread < 0 ? "+#{match.spread.abs}" : -1 * match.spread %> <br/>

      <% if match.open_for_betting? %>
        <%= form_with(model: WrestleBet::SpreadBet.new(match: match, wager: "away")) do |form| %>
          <%= form.hidden_field :match_id %>
          <%= form.hidden_field :wager %>

          <div>
            <%= form.submit "Bet on #{match.away_wrestler.name}" %>
          </div>
        <% end %>
      <% end %>
    </td>
  </tr>

  <% end %>


</table>
</div>
</div>

app/views/wrestle_bet/tournaments/display.html.erb
<div 
  id="wrestle_bet_match_display"
  tournament-path="<%= wrestle_bet_tournament_path(@match.tournament) %>"
  match-path="<%= wrestle_bet_match_path(@match) %>" >

<table>
  <tr>
    <td colspan='2'>
      <h1><%= @match.weight %> lbs</h1>
    </td>
  </tr>

  <tr>
    <td>
      <%= image_tag @match.home_wrestler.avatar.variant(:large), id: "home_wrestler" %><br/>
      <%= image_tag @match.home_wrestler.college.logo.variant(:thumb), class: "wrestle_bet_college" %><br/>
      <%= @match.home_wrestler.name %>
      ( <%= @match.home_wrestler.college.name %> )
    </td>
    <td>
      <%= image_tag @match.away_wrestler.avatar.variant(:large), id: "away_wrestler" %><br/>
      <%= image_tag @match.away_wrestler.college.logo.variant(:thumb), class: "wrestle_bet_college" %><br/>
      <%= @match.away_wrestler.name %>
      ( <%= @match.away_wrestler.college.name %> )
    </td>
  </tr>

  <tr>
    <td>
      <% @match.users_with_home_wagers.each do |user| %>
        <%= image_tag user.avatar.variant(:thumb) %>
      <% end %>
    </td>
    <td>
      <% @match.users_with_away_wagers.each do |user| %>
        <%= image_tag user.avatar.variant(:thumb) %>
      <% end %>
    </td>
  </tr>

  <tr>
    <td colspan='2'>
      <hr/>
      <div class="prop_bet_score">
        Jesus: <br/>
        <% @tournament.jesus.times do %>
          <%= image_tag "wrestle_bet/jesus.png", :size => '100x100'%> 
        <% end %>
      </div>

      <div class="prop_bet_score">
        Challenges: <br/>
        <% @tournament.challenges.times do %>
          <%= image_tag "wrestle_bet/challenge.png" , :size => '100x100'%>       
        <% end %>
      </div>

      <div class="prop_bet_score">
        Turns: <br/>
        <% @tournament.exposure.times do %>
          <%= image_tag "wrestle_bet/exposure.png", :size => "100x100" %> 
        <% end %>
      </div>
    </td>
  </tr>

</table>

<%= render partial: "prop_bet_animations" %>

</div>

app/views/wrestle_bet/tournaments/leaderboard.html.erb
<h1>The Leaderboard</h1>

<div 
  id="wrestle_bet_leaderboard"
  tournament-path="<%= wrestle_bet_tournament_path(@tournament) %>">

<ul>
  <% @rankings.each do |position, data| %>
    <li>
      <%= position.ordinalize %><br/>
      <%= data[:points] %> points<br/>
      <% data[:users].each do |user| %>
        <%= user.email %><br/>
      <% end %>
    </li>
  <% end %>
</ul>

</div>

app/views/wrestle_bet/tournaments/scorecard.html.erb
<div 
  id="wrestle_bet_leaderboard"
  tournament-path="<%= wrestle_bet_tournament_path(@tournament) %>">

<table>
  <tr>
      <th></th>
      <th></th>
      <th>Total</th>
      <% @tournament.weights.each do |weight| %>
        <th><%= weight %></th>
      <% end %>
      <th>
        <%= image_tag "wrestle_bet/jesus.png", :size => '100x100'%> 
      </th>
      <th>
          <%= image_tag "wrestle_bet/exposure.png", :size => "100x100" %> 
      </th>
      <th>
        <%= image_tag "wrestle_bet/challenge.png" , :size => '100x100'%>       
      </th>
  </tr>
  
  <% @leaderboard.users.each do |user| %>
    <tr class="wrestle_bet_first_place_<%= @leaderboard.user_in_first_place?(user) %>">
      <th>
        <%= user.handle %>
        <% if @leaderboard.user_in_first_place?(user) %>
          <%= image_tag "wrestle_bet/trophy.png", size: "25x25" %>
        <% end %>
      </th>
      <td>
        <%= image_tag user.avatar.variant(:small_thumb) %><br/>
      </td>
      <td class="total_score_for_user"><%= @leaderboard.score_for_user(user) %></td>
      <% @tournament.weights.each do |weight| %>
        <% result = @leaderboard.score_for_weight(user, weight) %>
        <td class="spread_bet_result_<%= result %>">
          <% if result == 1 %>
            <%= image_tag "wrestle_bet/green_check.png", size: "25x25"%>
          <% elsif @tournament.weight_is_completed?(weight) %>
            <%= image_tag "wrestle_bet/red_x.png", size: "25x25"%>
          <% end %>
        </td>
      <% end %>

      <% [:jesus, :exposure, :challenges].each do |prop| %>
        <% result = @leaderboard.score_for_prop(user, prop) %>
        <td class="prop_bet_result_<%= result %>">
          <% if result == 1 %>
            <%= image_tag "wrestle_bet/green_check.png", size: "25x25"%>
          <% elsif @tournament.completed? %>
            <%= image_tag "wrestle_bet/red_x.png", size: "25x25"%>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>

</table>

<%= render partial: "prop_bet_animations" %>

</div>

app/views/wrestle_bet/tournaments/user_links.html.erb
<h1>Users</h1>

<table>
  <% User.all.each do |user| %>
    <tr>
      <td>
        <% if user.avatar.attached? %>
          <%= image_tag user.avatar.variant(:thumb) %>
        <% end %>
      </td>

      <td>
        <%= user_betslip_link(user, @tournament) %>
      </td>

      <td>
        <% if user.wrestle_bet_prop_bet.present? %>
          jesus: <%= user.wrestle_bet_prop_bet.jesus %>,
          turns: <%= user.wrestle_bet_prop_bet.exposure %>,
          chall: <%= user.wrestle_bet_prop_bet.challenges %>,
        <% end %>
      </td>

      <td>
        <% user.wrestle_bet_bets.all.sort_by { |b| b.match.weight }.each do |bet| %>
          <%= bet.match.weight %>: <%= bet.wager %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>