config/routes.rb
Rails.application.routes.draw do
  namespace :olympics do
    resources :teams
    resources :matches, only: [:index, :update]

    get "/scoreboard", to: "scoreboard#scoreboard"
    get "/generate_brackets", to: "scoreboard#generate_form"
    post "/generate_brackets", to: "scoreboard#generate_brackets"
    get "/fetch_now_playing" => 'scoreboard#fetch_now_playing', as: 'fetch_now_playing'
    get "/fetch_on_deck" => 'scoreboard#fetch_on_deck'
    get "/fetch_rankings" => 'scoreboard#fetch_rankings'
    get "/fetch_tiebreaker" => 'scoreboard#fetch_tiebreaker'
    get "/fetch_latest_updated_at" => 'scoreboard#fetch_latest_updated_at'
  end

  namespace :advocate do
    get "/schedule", to: "schedule#show"
    get "/aggregate_report", to: "schedule#aggregate_report"
    get "/monthly_report", to: "schedule#monthly_report"
  end

  namespace :etoh do
    get "/drinks", to: "drinks#index"
    post "/drinks", to: "drinks#create"
    get "/delete_drink", to: "drinks#destroy"
  end

  namespace :wrestle_bet do
    resources :prop_bets
    resources :spread_bets
    resources :matches
    resources :wrestlers
    resources :tournaments, only: [:update, :show]
    get "/tournaments", to: "tournaments#index"
    get "/tournaments/:id/betslip", to: "tournaments#betslip", as: :betslip
    get "/tournaments/:id/display", to: "tournaments#display", as: :display
    get "/tournaments/:id/user_links", to: "tournaments#user_links", as: :user_links
    get "/tournaments/:id/scorecard", to: "tournaments#scorecard", as: :scorecard
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  get "/access_denied", to: "application#access_denied"

  #### <Wrestling>
  root "matches#index"

  get "/individual_rankings/:weight", to: "wrestlers#individual_rankings", as: "individual_rankings"

  get "/matches/preview", to: "matches#preview", as: "preview"
  get "/matches/:id", to: "matches#edit", as: "match"
  patch "/matches/:id", to: "matches#update", as: "update_match"

  get "/colleges", to: "colleges#index", as: "colleges"
  get "/colleges/:id", to: "colleges#show", as: "college"
  #### </Wrestling>
end

app/models/college.rb
class College < ApplicationRecord
  has_many :wrestlers, -> { order("weight ASC") }
  has_many :home_matches, class_name: "Match", foreign_key: "home_team_id", dependent: :destroy
  has_many :away_matches, class_name: "Match", foreign_key: "away_team_id", dependent: :destroy
  validates_uniqueness_of :name

  has_one_attached :logo do |attachable|
    attachable.variant :thumb, resize_to_fill: [100, 100]
  end

  after_commit :add_default_logo, on: [:create, :update]

  EQUIVALENCIES = [
    # [Canonical, alias_1, alias_2, ...],
    ["UNI", "Northern Iowa"],
    ["App State", "Appalachian State"],
    ["ND State", "North Dakota State"],
    ["SD State", "South Dakota State"],
    ["OK State", "Oklahoma State"],
    ["SIUE", "SIU Edwardsville"],
    ["Penn", "Pennsylvania"],
    ["Army", "Army West Point"],
    ["Northern Colorado", "N. Colorado"],
  ].inject({}) do |acc, names|
    canonical = names[0]
    names[1..].each do |alternate|
      acc[alternate] = canonical
    end

    acc
  end

  def self.find_or_create_by_corrected_name(name)
    if EQUIVALENCIES.has_key?(name)
      Rails.logger.info "Correcting: #{name} => #{EQUIVALENCIES[name]}"
      name = EQUIVALENCIES[name]
    end

    College.find_or_create_by(name: name)
  end

  def self.find_by_corrected_name!(name)
    if EQUIVALENCIES.has_key?(name)
      Rails.logger.info "Correcting: #{name} => #{EQUIVALENCIES[name]}"
      name = EQUIVALENCIES[name]
    end

    college = College.find_by(name: name)
    unless college.present?
      msg = "Unable to find college: '#{name}'"
      msg += "\nAdd mapping to EQUIVALENCIES in app/models/college.rb"
      raise msg
    end

    college
  end

  def matches
    Match.where("home_team_id = :id OR away_team_id = :id", id: id).order(date: "ASC")
  end

  private def add_default_logo
    unless logo.attached?
      file_name = "default_college_logo.png"
      default_logo_path = Rails.root.join("app", "assets", "images", file_name)
      self.logo.attach(
        io: File.open(default_logo_path),
        filename: file_name
      )
    end
  end
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController

  def show
    @college = College.find(params[:id])
  end

  def index
    @last_updated_at = College
      .maximum("updated_at")
      .in_time_zone("Central Time (US & Canada)")
      .strftime("%Y-%m-%d %H:%M")
    @colleges = College.order(:dual_rank).order(:tournament_rank).all
  end
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/views/colleges/index.html.erb
<p>
  Updated at <%= @last_updated_at %>
</p>

<table>
  <tr>
    <th>College</th>
    <th>Dual Rank</th>
    <th>Tournament Rank</th>
    <th>Schedule</th>
  </tr>

  <% @colleges.each do |college| %>
    <tr>
      <td><%= college.name %></td>
      <td><%= college.dual_rank %></td>
      <td><%= college.tournament_rank %></td>
      <td>
        <%= link_to("Schedule (#{college.matches.count})", college_path(college)) %>
      </td>
    </tr>
  <% end %>

</table>

app/views/colleges/show.html.erb
<h1><%= @college.name %></h1>

<p>
  <%= link_to("Schedule", @college.url, target: :_blank) %>
</p>

<h3>Schedule</h3>
<table>
  <tr>
    <th>Date</th>
    <th>Away</th>
    <th>Home</th>
    <th>Watch</th>
    <th>...</th>
  </tr>

  <% @college.matches.each do |match| %>
    <tr>
      <td><%= match.date.strftime("%A %m/%d") %></td>
      <td><%= name_with_rank(match.away_team) %></td>
      <td><%= name_with_rank(match.home_team) %></td>
      <td>
        <% if match.time %>
          <%= match.time.strftime("%l:%M%p") %>
        <% end %>

        <% if match.watch_on %>
          <%= match.watch_on %>
        <% end %>
      </td>
      <td>
        <%= link_to "...", match_path(id: match.id) %>
      </td>
    </tr>
  <% end %>

</table>

<h3>Ranked Wrestlers</h3>
<table>
  <% @college.wrestlers.each do |wrestler| %>
    <tr>
      <td><%= wrestler.weight %></td>
      <td><%= wrestler.name %> (<%= wrestler.rank %>)</td>
      <td><%= wrestler.year %></td>
    </tr>
  <% end %>
</table>