config/routes.rb
Rails.application.routes.draw do
  namespace :olympics do
    resources :teams
    resources :matches, only: [:index, :update]

    get "/scoreboard", to: "scoreboard#scoreboard"
    get "/generate_brackets", to: "scoreboard#generate_form"
    post "/generate_brackets", to: "scoreboard#generate_brackets"
    get "/fetch_now_playing" => 'scoreboard#fetch_now_playing', as: 'fetch_now_playing'
    get "/fetch_on_deck" => 'scoreboard#fetch_on_deck'
    get "/fetch_rankings" => 'scoreboard#fetch_rankings'
    get "/fetch_tiebreaker" => 'scoreboard#fetch_tiebreaker'
    get "/fetch_latest_updated_at" => 'scoreboard#fetch_latest_updated_at'
  end

  namespace :advocate do
    get "/schedule", to: "schedule#show"
    get "/aggregate_report", to: "schedule#aggregate_report"
    get "/monthly_report", to: "schedule#monthly_report"
  end

  namespace :etoh do
    get "/drinks", to: "drinks#index"
    post "/drinks", to: "drinks#create"
    get "/delete_drink", to: "drinks#destroy"
  end

  namespace :wrestle_bet do
    resources :prop_bets
    resources :spread_bets
    resources :matches
    resources :wrestlers
    resources :tournaments, only: [:update, :show]
    get "/tournaments", to: "tournaments#index"
    get "/tournaments/:id/betslip", to: "tournaments#betslip", as: :betslip
    get "/tournaments/:id/display", to: "tournaments#display", as: :display
    get "/tournaments/:id/user_links", to: "tournaments#user_links", as: :user_links
    get "/tournaments/:id/scorecard", to: "tournaments#scorecard", as: :scorecard
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    get "/users/sign_out", to: "devise/sessions#destroy"
  end
  get "/access_denied", to: "application#access_denied"

  #### <Wrestling>
  root "matches#index"

  get "/individual_rankings/:weight", to: "wrestlers#individual_rankings", as: "individual_rankings"

  get "/matches/preview", to: "matches#preview", as: "preview"
  get "/matches/:id", to: "matches#edit", as: "match"
  patch "/matches/:id", to: "matches#update", as: "update_match"

  get "/colleges", to: "colleges#index", as: "colleges"
  get "/colleges/:id", to: "colleges#show", as: "college"
  #### </Wrestling>
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_team, class_name: "College", foreign_key: "home_team_id"
  belongs_to :away_team, class_name: "College", foreign_key: "away_team_id"

  TOP_MATCHUP_LIMIT = 15

  def top_matchups
    WrestlerService::WEIGHTS.inject([]) do |acc, weight|
      home_wrestler = home_team.wrestlers.find { |w| w.weight == weight }
      away_wrestler = away_team.wrestlers.find { |w| w.weight == weight }

      if home_wrestler.present? && away_wrestler.present? &&
          home_wrestler.rank.present? && away_wrestler.rank.present? &&
          home_wrestler.rank <= TOP_MATCHUP_LIMIT && away_wrestler.rank <= TOP_MATCHUP_LIMIT
        acc << [away_wrestler, home_wrestler]
      end

      acc
    end
  end

  def to_s
    "#{id} : #{away_team.name} @ #{home_team.name} (#{watch_on}, #{time}, #{date})"
  end
end

app/models/olympics/match.rb
class Olympics::Match < ApplicationRecord
  belongs_to :team_1, class_name: "Olympics::Team"
  belongs_to :team_2, class_name: "Olympics::Team"
  belongs_to :winning_team, class_name: "Olympics::Team", optional: true

  validates_presence_of :bout_number

  module Events
    EVENTS = [
      BEER_PONG = "beer_pong",
      FLIP_CUP = "flip_cup",
      QUARTERS = "quarters",
      DRINK_BALL = "drink_ball",
    ]
  end

  def to_s
    "#{team_1} #{team_2} : #{event}"
  end
end

app/models/wrestle_bet.rb
module WrestleBet
  def self.table_name_prefix
    "wrestle_bet_"
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, except: [:index]

  def index
    @lookback_window = if params.has_key?(:lookback_window)
      params[:lookback_window].to_i
    else
      2
    end
    today = Date.today.in_time_zone("Central Time (US & Canada)")

    @matches = Match
      .where("date >= ?", today - @lookback_window.days)
      .order(:date).order(:time).order(:watch_on)
      .all

    @limit_to_rank = params[:limit_to_rank].to_i
    if @limit_to_rank > 0
      @matches = @matches.filter do |match|
        (match.home_team.dual_rank || 100) <= @limit_to_rank &&
          (match.away_team.dual_rank || 100) <= @limit_to_rank
      end
    end
  end

  def edit
  end

  def update
    if @match.update(match_params)
      redirect_to @match, notice: "Match was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def set_match
      match_id = params[:id] || params[:match_id]
      @match = Match.find(match_id)
      @preview = MatchService.preview(@match.away_team, @match.home_team)
      @home = @preview[:home]
      @away = @preview[:away]
      @prediction = @preview[:prediction]
    end

    def match_params
      params.require(:match).permit(:time, :watch_on)
    end
end

app/controllers/olympics/matches_controller.rb
class Olympics::MatchesController < Olympics::ApplicationController
  before_action :set_match, only: %i[ update ]

  def index
    @now_playing = Olympics::Match
      .where("now_playing")
      .order(:bout_number)
      .all

    @open_matches = Olympics::Match
      .where("winning_team_id is null")
      .where("not now_playing")
      .order(:bout_number)
      .all

    @closed_matches = Olympics::Match
      .where("winning_team_id is not null")
      .order("bout_number DESC")
      .all
  end

  def update
    respond_to do |format|
      if Olympics::MatchService.update(@match, match_params)
        notice = "Match #{@match.bout_number} was successfully updated."
        format.html { redirect_to olympics_matches_url, notice: notice }
      else
        alert = "Failed to update match #{@match.bout_number}"
        format.html { redirect_to olympics_matches_url, alert: alert }
      end
    end
  end

  def set_match
    @match = Olympics::Match.find(params[:id])
  end

  def match_params
    params.require(:olympics_match).permit(:winning_team_id, :now_playing, :bp_cups_remaining)
  end
end

app/controllers/wrestle_bet/application_controller.rb
class WrestleBet::ApplicationController < ApplicationController
  layout "wrestle_bet/application"
  before_action :set_tournament

  def set_tournament
    @tournament = WrestleBet::Tournament.first
  end
end

app/controllers/wrestle_bet/matches_controller.rb
class WrestleBet::MatchesController < WrestleBet::ApplicationController
  before_action :set_wrestle_bet_match, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_admin!, only: [:show]

  # GET /wrestle_bet/matches or /wrestle_bet/matches.json
  def index
    @wrestle_bet_matches = WrestleBet::Match.order("weight ASC")
      .all
      .sort_by { |m| m.completed? ? 1 : 0 }

    @tournament = WrestleBet::Tournament.first!
  end

  # GET /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def show
    respond_to do |format|
      format.html { render  }
      format.json do
        render json: @wrestle_bet_match.as_json(
          only: [:id, :home_score, :away_score]
        )
      end
    end
  end

  # GET /wrestle_bet/matches/new
  def new
    @wrestle_bet_match = WrestleBet::Match.new
  end

  # GET /wrestle_bet/matches/1/edit
  def edit
  end

  # POST /wrestle_bet/matches or /wrestle_bet/matches.json
  def create
    @wrestle_bet_match = WrestleBet::Match.new(wrestle_bet_match_params)

    respond_to do |format|
      if @wrestle_bet_match.save
        format.html { redirect_to wrestle_bet_match_url(@wrestle_bet_match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @wrestle_bet_match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_match.update(wrestle_bet_match_params)
        format.html { redirect_to wrestle_bet_matches_url, notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @wrestle_bet_match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/matches/1 or /wrestle_bet/matches/1.json
  def destroy
    @wrestle_bet_match.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_match
      @wrestle_bet_match = WrestleBet::Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_match_params
      params.require(:wrestle_bet_match).permit(:weight, :started, :home_wrestler_id, :away_wrestler_id, :home_score, :away_score, :tournament_id, :spread)
    end
end

app/controllers/wrestle_bet/prop_bets_controller.rb
class WrestleBet::PropBetsController < WrestleBet::ApplicationController
  skip_before_action :authenticate_admin!, only: [:create, :update]
  before_action :authenticate_user!, only: [:create, :update]
  before_action :set_wrestle_bet_prop_bet, only: %i[ show edit update destroy ]
  before_action :verify_tournament_has_not_started, only: %i[ create update ]

  # GET /wrestle_bet/prop_bets or /wrestle_bet/prop_bets.json
  def index
    @wrestle_bet_prop_bets = WrestleBet::PropBet.all
  end

  # GET /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def show
  end

  # POST /wrestle_bet/prop_bets or /wrestle_bet/prop_bets.json
  def create
    @bet = WrestleBet::PropBet.new(wrestle_bet_prop_bet_params)
    @bet.user_id = current_user.id
    WrestleBet::PropBet.where(
      user_id: current_user.id,
      tournament_id: @bet.tournament_id,
    ).destroy_all

    respond_to do |format|
      if @bet.save
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.tournament_id),
          notice: "Prop bets updated"
        }
        format.json { render :show, status: :created, location: @bet }
      else
        @bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.tournament_id),
          alert: "failed to place bet"
        }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_prop_bet.update(wrestle_bet_prop_bet_params)
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @wrestle_bet_prop_bet.tournament_id),
          notice: "Prop bets updated"
        }
        format.json { render :show, status: :ok, location: @wrestle_bet_prop_bet }
      else
        @wrestle_bet_prop_bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @wrestle_bet_prop_bet.tournament_id),
          alert: "failed to update prop bets"
        }
        format.json { render json: @wrestle_bet_prop_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/prop_bets/1 or /wrestle_bet/prop_bets/1.json
  def destroy
    @wrestle_bet_prop_bet.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_prop_bets_url, notice: "Prop bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_prop_bet
      @wrestle_bet_prop_bet = WrestleBet::PropBet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_prop_bet_params
      params.require(:wrestle_bet_prop_bet).permit(:tournament_id, :jesus, :exposure, :challenges)
    end

    def verify_tournament_has_not_started
      @tournament = WrestleBet::Tournament.find(wrestle_bet_prop_bet_params[:tournament_id])
      if @tournament.started?
          redirect_to wrestle_bet_betslip_url(id: @tournament.id),
            alert: "Tournament has already started"
      end
    end
end

app/controllers/wrestle_bet/spread_bets_controller.rb
class WrestleBet::SpreadBetsController < WrestleBet::ApplicationController
  skip_before_action :authenticate_admin!, only: [:create]
  before_action :authenticate_user!, only: [:create]

  before_action :set_wrestle_bet_spread_bet, only: %i[ show edit update destroy ]

  before_action :verify_match_has_not_started, only: %i[ create ]

  # GET /wrestle_bet/spread_bets or /wrestle_bet/spread_bets.json
  def index
    @wrestle_bet_spread_bets = WrestleBet::SpreadBet.all
  end

  # GET /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def show
  end

  # GET /wrestle_bet/spread_bets/new
  def new
    @wrestle_bet_spread_bet = WrestleBet::SpreadBet.new
  end

  # GET /wrestle_bet/spread_bets/1/edit
  def edit
  end

  # POST /wrestle_bet/spread_bets or /wrestle_bet/spread_bets.json
  def create
    @bet = WrestleBet::SpreadBet.new(wrestle_bet_spread_bet_params)
    @bet.user_id = current_user.id
    WrestleBet::SpreadBet.where(
      user_id: current_user.id,
      match_id: @bet.match_id,
    ).destroy_all

    respond_to do |format|
      if @bet.save
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.match.tournament_id),
          notice: "#{@bet.label} placed"
        }
        format.json { render json: {status: :created}, status: :created }
      else
        @bet.errors.each do |field, message|
          Rails.logger.info("Failed to save bet: #{field}-#{message}")
        end
        format.html {
          redirect_to wrestle_bet_betslip_url(id: @bet.match.tournament_id),
          alert: "failed to place bet"
        }
        format.json { render json: @bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def update
    respond_to do |format|
      if @wrestle_bet_spread_bet.update(wrestle_bet_spread_bet_params)
        format.html { redirect_to wrestle_bet_spread_bet_url(@wrestle_bet_spread_bet), notice: "Spread bet was successfully updated." }
        format.json { render :show, status: :ok, location: @wrestle_bet_spread_bet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wrestle_bet_spread_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrestle_bet/spread_bets/1 or /wrestle_bet/spread_bets/1.json
  def destroy
    @wrestle_bet_spread_bet.destroy

    respond_to do |format|
      format.html { redirect_to wrestle_bet_spread_bets_url, notice: "Spread bet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrestle_bet_spread_bet
      @wrestle_bet_spread_bet = WrestleBet::SpreadBet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wrestle_bet_spread_bet_params
      params.require(:wrestle_bet_spread_bet).permit(:match_id, :wager)
    end

    def verify_match_has_not_started
      @match = WrestleBet::Match.find(wrestle_bet_spread_bet_params[:match_id])
      if @match.started?
        respond_to do |format|
          format.html {
            redirect_to wrestle_bet_betslip_url(id: @match.tournament_id),
              alert: "Match has already started"
          }
          format.json {
            render json: {error: "Match has already started"}, status: 422
          }
        end
      end
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
  def name_with_rank(college)
    result = college.name
    if college.dual_rank
      result += " (#{college.dual_rank})"
    end

    result
  end
end

app/helpers/olympics/matches_helper.rb
module Olympics::MatchesHelper
  def event_logo(match, options={})
    image_name = case match.event
    when Olympics::Match::Events::BEER_PONG
      "beer_pong.jpeg"
    when Olympics::Match::Events::FLIP_CUP
      "flip_cup.png"
    when Olympics::Match::Events::QUARTERS
      "quarter.png"
    when Olympics::Match::Events::DRINK_BALL
      "drink_ball.png"
    else
      raise "no event #{match.event} found in event_logo()"
    end

    options = {class: "event_logo"}
    image_tag "olympics/#{image_name}", options
  end

  def bp_cup_diff(match, team)
    return "" if match.winning_team_id.nil?
    return "" unless match.event == Olympics::Match::Events::BEER_PONG

    diff = if match.winning_team == team
      "+#{match.bp_cups_remaining}"
    else
      "-#{match.bp_cups_remaining}"
    end

    "<br/>#{diff}".html_safe
  end
end

app/helpers/wrestle_bet/matches_helper.rb
module WrestleBet::MatchesHelper
end

app/views/wrestle_bet/matches/_form.html.erb
<%= form_with(model: wrestle_bet_match) do |form| %>
  <% if wrestle_bet_match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wrestle_bet_match.errors.count, "error") %> prohibited this wrestle_bet_match from being saved:</h2>

      <ul>
        <% wrestle_bet_match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :weight, style: "display: block" %>
    <%= form.number_field :weight %>
  </div>

  <div>
    <%= form.label :started, style: "display: block" %>
    <%= form.check_box :started %>
  </div>

  <div>
    <%= form.label :home_wrestler_id, style: "display: block" %>
    <%= form.number_field :home_wrestler_id %>
  </div>

  <div>
    <%= form.label :away_wrestler_id, style: "display: block" %>
    <%= form.number_field :away_wrestler_id %>
  </div>

  <div>
    <%= form.label :home_score, style: "display: block" %>
    <%= form.number_field :home_score %>
  </div>

  <div>
    <%= form.label :away_score, style: "display: block" %>
    <%= form.number_field :away_score %>
  </div>

  <div>
    <%= form.label :spread, style: "display: block" %>
    <%= form.number_field :spread, step: :any %>
  </div>

  <div>
    <%= form.label :tournament_id, style: "display: block" %>
    <%= form.number_field :tournament_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wrestle_bet/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <p>
    <%= match.weight %> lbs

    in <%= match.tournament.name %>
  </p>

  <p>
    <strong>Started?</strong>
    <%= match.started %>
  </p>

  <p>
    <%= match.home_wrestler.name %>
    vs.
    <%= match.away_wrestler.name %>
  </p>

  <p>
    Current Score:<br/>
    <%= match.home_score %>
    -
    <%= match.away_score %>
  </p>

  <p>
    spread: <%= match.spread %>
  </p>

</div>

app/views/wrestle_bet/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", wrestle_bet_match: @wrestle_bet_match %>

<br>

<div>
  <%= link_to "Show this match", @wrestle_bet_match %> |
  <%= link_to "Back to matches", wrestle_bet_matches_path %>
</div>

app/views/wrestle_bet/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches</h1>

<p>
<%= link_to "New match", new_wrestle_bet_match_path %>
</p>

<p>
  Prop Bets<br/>
  <%= form_with(model: @tournament) do |form| %>
    <div>
      <%= form.hidden_field :tournament_id %>
    </div>

    <div>
      <%= form.label :jesus, style: "display: block" %>
      <%= form.number_field :jesus %>
    </div>

    <div>
      <%= form.label :exposure, style: "display: block" %>
      <%= form.number_field :exposure %>
    </div>

    <div>
      <%= form.label :challenges, style: "display: block" %>
      <%= form.number_field :challenges %>
    </div>

    <div>
      <%= form.submit "Save Prop Bet Tallies" %>
    </div>
  <% end %>
</p>

<div id="wrestle_bet_matches">
  <% @wrestle_bet_matches.each do |wrestle_bet_match| %>
    <h3><%= wrestle_bet_match.title %> (<%= wrestle_bet_match.spread %>)</h3>
    <%= form_with(model: wrestle_bet_match) do |form| %>
      <div>
        <%= form.label :started, style: "display: block" %>
        <%= form.check_box :started %>
      </div>

      <div>
        <%= form.label :home_score, wrestle_bet_match.home_wrestler.name + " (home)", style: "display: block" %>
        <%= form.number_field :home_score %>
      </div>

      <div>
        <%= form.label :away_score, wrestle_bet_match.away_wrestler.name + " (away)", style: "display: block" %>
        <%= form.number_field :away_score %>
      </div>

      <div>
        <%= form.submit "Update #{wrestle_bet_match.short_title}" %>
      </div>
    <% end %>
    <%= link_to "Edit", edit_wrestle_bet_match_path(wrestle_bet_match) %>
  <% end %>
</div>

app/views/wrestle_bet/matches/new.html.erb
<h1>New match</h1>

<%= render "form", wrestle_bet_match: @wrestle_bet_match %>

<br>

<div>
  <%= link_to "Back to matches", wrestle_bet_matches_path %>
</div>

app/views/wrestle_bet/matches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wrestle_bet_match %>

<div>
  <%= link_to "Back to matches", wrestle_bet_matches_path %>
  <%= link_to "Edit", edit_wrestle_bet_match_path(@wrestle_bet_match) %>

  <%= button_to "Destroy this match", @wrestle_bet_match, method: :delete %>
</div>